spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5433/podcazity
    username: [username]
    password: [password]