spring:
  jpa: 
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: false
  datasource:
    url: jdbc:postgresql://[server]:[port]/[database]
    username: [user]
    password: [password]  