spring:
  jpa: 
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/podcazity
    username: postgres
    password: admin