spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: false
  datasource:
    url: [url]
    username: [username]
    password: [password]
logging:
  level:
    org.springframework.web: ERROR
    net.virux: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: log/application.log